from RegisterFrame import *
from StartFrame import *
from MenuFrame import *
from SubjectFrame import *
from UserFrame import *
from CreateEventFrame import *
from TimeSelectFrame import *
from CalendarFrame import *
from ActivitiesFrame import *
